export const defaultStepsData = [
    {
        id: "step-1",
        name: "Transportbedarf überprüfen",
        person: "employee-1",
        personMonthlySalary: 5000,
        costDriver: "Anzahl der Transportanfragen",
        costDriverValue: 30,
        stepDuration: 5,
        additionalResources: "resource-1",
        additionalResourcesValue: 1120,
    },
    {
        id: "step-2",
        name: "Angebot vorbereiten und übermitteln",
        person: "employee-1",
        personMonthlySalary: 5000,
        costDriver: "Anzahl Transportbedarfe",
        costDriverValue: 25,
        stepDuration: 10,
        additionalResources: "resource-1",
        additionalResourcesValue: 1120,
    },
    {
        id: "step-3",
        name: "Transportbedarf erfassen",
        person: "employee-1",
        personMonthlySalary: 5000,
        costDriver: "Anzahl Angebote",
        costDriverValue: 24,
        stepDuration: 22,
        additionalResources: "resource-2",
        additionalResourcesValue: 1300,
    },
    {
        id: "step-4",
        name: "Verfügbarkeit von Personal und Fuhrpark überprüfen",
        person: "employee-2",
        personMonthlySalary: 4500,
        costDriver: "Anzahl Aufträge",
        costDriverValue: 22,
        stepDuration: 7,
        additionalResources: "resource-9",
        additionalResourcesValue: 4000,
    },
    {
        id: "step-5",
        name: "Touren planen",
        person: "employee-3",
        personMonthlySalary: 5000,
        costDriver: "Anzahl Touren",
        costDriverValue: 7,
        stepDuration: 30,
        additionalResources: "resource-9",
        additionalResourcesValue: 4000,
    },
    {
        id: "step-6",
        name: "Touren, Fahrzeuge und employee-4 disponieren",
        person: "employee-2",
        personMonthlySalary: 4500,
        costDriver: "Anzahl Touren",
        costDriverValue: 7,
        stepDuration: 12,
        additionalResources: "resource-9",
        additionalResourcesValue: 4000,
    },
    {
        id: "step-7",
        name: "Frachtpapiere vorbereiten (und ausdrucken)",
        person: "employee-2",
        personMonthlySalary: 4500,
        costDriver: "Anzahl Touren",
        costDriverValue: 7,
        stepDuration: 10,
        additionalResources: "resource-9",
        additionalResourcesValue: 4000,
    },
    {
        id: "step-8",
        name: "Dokumentenübergabe und Instruktionen an employee-4",
        person: "employee-2",
        personMonthlySalary: 4500,
        costDriver: "Anzahl Touren",
        costDriverValue: 7,
        stepDuration: 6,
        additionalResources: "resource-1",
        additionalResourcesValue: 1120,
    },
    {
        id: "step-9",
        name: "Zum Abhol-WA fahren",
        person: "employee-4",
        personMonthlySalary: 3900,
        costDriver: "Anzahl Fahrten",
        costDriverValue: 22,
        stepDuration: 42,
        additionalResources: "resource-4",
        additionalResourcesValue: 75000,
    },
    {
        id: "step-10",
        name: "Verladepapiere an Erfassung übergeben",
        person: "employee-4",
        personMonthlySalary: 3900,
        costDriver: "Anzahl Fahrten",
        costDriverValue: 22,
        stepDuration: 7,
        additionalResources: "",
        additionalResourcesValue: 0,
    },
    {
        id: "step-11",
        name: "Beladeplatz zuweisen",
        person: "employee-2",
        personMonthlySalary: 4500,
        costDriver: "Anzahl Touren",
        costDriverValue: 7,
        stepDuration: 5,
        additionalResources: "",
        additionalResourcesValue: 0,
    },
    {
        id: "step-12",
        name: "Sendung überprüfen (visuell)",
        person: "employee-4",
        personMonthlySalary: 3900,
        costDriver: "Anzahl Sendungen",
        costDriverValue: 45,
        stepDuration: 4,
        additionalResources: "",
        additionalResourcesValue: 0,
    },
    {
        id: "step-13",
        name: "LKW am Versandort beladen und Ladung sichern",
        person: "employee-4",
        personMonthlySalary: 3900,
        costDriver: "Anzahl Sendungen",
        costDriverValue: 45,
        stepDuration: 35,
        additionalResources: "resource-6",
        additionalResourcesValue: 400,
    },
    {
        id: "step-14",
        name: "Sendung überprüfen (visuell)",
        person: "employee-4",
        personMonthlySalary: 3900,
        costDriver: "Anzahl Touren",
        costDriverValue: 7,
        stepDuration: 1,
        additionalResources: "resource-3",
        additionalResourcesValue: 700,
    },
    {
        id: "step-15",
        name: "Fahrzeugzustand prüfen und vorbereiten",
        person: "employee-4",
        personMonthlySalary: 3900,
        costDriver: "Anzahl Touren",
        costDriverValue: 7,
        stepDuration: 3,
        additionalResources: "resource-11",
        additionalResourcesValue: 200,
    },
    {
        id: "step-16",
        name: "Sendung transportieren",
        person: "employee-4",
        personMonthlySalary: 3900,
        costDriver: "Anzahl Fahrten",
        costDriverValue: 22,
        stepDuration: 85,
        additionalResources: "resource-4",
        additionalResourcesValue: 75700,
    },
    {
        id: "step-17",
        name: "Zum Entlade-WE fahren",
        person: "employee-4",
        personMonthlySalary: 3900,
        costDriver: "Anzahl Fahrten",
        costDriverValue: 22,
        stepDuration: 3,
        additionalResources: "resource-4",
        additionalResourcesValue: 75700,
    },
    {
        id: "step-18",
        name: "Entladepapiere an Erfassung übergeben",
        person: "employee-4",
        personMonthlySalary: 3900,
        costDriver: "Anzahl Fahrten",
        costDriverValue: 22,
        stepDuration: 7,
        additionalResources: "",
        additionalResourcesValue: 0,
    },
    {
        id: "step-19",
        name: "Entladeplatz zuweisen",
        person: "employee-4",
        personMonthlySalary: 3900,
        costDriver: "Anzahl Fahrten",
        costDriverValue: 22,
        stepDuration: 5,
        additionalResources: "",
        additionalResourcesValue: 0,
    },
    {
        id: "step-20",
        name: "Sendung beim Empfänger abladen",
        person: "employee-4",
        personMonthlySalary: 3900,
        costDriver: "Anzahl Fahrten",
        costDriverValue: 22,
        stepDuration: 20,
        additionalResources: "resource-11",
        additionalResourcesValue: 200,
    },
    {
        id: "step-21",
        name: "Sendungen scannen",
        person: "employee-4",
        personMonthlySalary: 3900,
        costDriver: "Anzahl Sendungen",
        costDriverValue: 45,
        stepDuration: 3,
        additionalResources: "resource-7",
        additionalResourcesValue: 180,
    },
    {
        id: "step-22",
        name: "Lieferscheine und Bordeos vom Kunden quittieren lassen",
        person: "employee-4",
        personMonthlySalary: 3900,
        costDriver: "Anzahl Fahrten",
        costDriverValue: 22,
        stepDuration: 5,
        additionalResources: "",
        additionalResourcesValue: 0,
    },
    {
        id: "step-23",
        name: "Zurück zum Fuhrpark fahren und die employee-4karte auslesen lassen",
        person: "employee-4",
        personMonthlySalary: 3900,
        costDriver: "Anzahl Touren",
        costDriverValue: 7,
        stepDuration: 40,
        additionalResources: "resource-4",
        additionalResourcesValue: 75700,
    },

    {
        id: "step-24",
        name: "Dokumente an employee-2en übergeben (Schadensbericht, Beschwerden)",
        person: "employee-4",
        personMonthlySalary: 3900,
        costDriver: "Anzahl Touren",
        costDriverValue: 7,
        stepDuration: 7,
        additionalResources: "resource-1",
        additionalResourcesValue: 1120,
    },
    {
        id: "step-25",
        name: "Transport dokumentieren und analysieren",
        person: "employee-2",
        personMonthlySalary: 4500,
        costDriver: "Anzahl Touren",
        costDriverValue: 7,
        stepDuration: 10,
        additionalResources: "resource-9",
        additionalResourcesValue: 4000,
    },
    {
        id: "step-26",
        name: "Rechnung erstellen und verbuchen",
        person: "employee-2",
        personMonthlySalary: 4500,
        costDriver: "Anzahl Aufträge",
        costDriverValue: 22,
        stepDuration: 7,
        additionalResources: "resource-2",
        additionalResourcesValue: 1300,
    },
    {
        id: "step-27",
        name: "Debitorenabrechnung durchführen",
        person: "employee-2",
        personMonthlySalary: 4500,
        costDriver: "Anzahl Aufträge",
        costDriverValue: 22,
        stepDuration: 4,
        additionalResources: "resource-8",
        additionalResourcesValue: 500,
    },
    {
        id: "step-28",
        name: "Zahlungseingang prüfen",
        person: "employee-2",
        personMonthlySalary: 4500,
        costDriver: "Anzahl Aufträge",
        costDriverValue: 22,
        stepDuration: 3,
        additionalResources: "resource-8",
        additionalResourcesValue: 500,

    },
];
